### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by 30000lightyears** [stripedypaper/stripedypaper.github.io#7]
Hi I want to help on translation about Arknights guesser to Chinese, how can I contribute or contact you?

**Comment by stripedypaper** [comment]
Hi @30000lightyears very sorry I didn't see this issue until now. One reason I did not have zh_CN support originally is that the repo I use for images https://github.com/Aceship/Arknight-Images/tree/main/characters doesn't have many CN operators. In fact, it's pretty out of date  even for EN at the moment. Do you know a repo that has up to date image assets for CN?

**Comment by stripedypaper** [comment]
Ah I might be able to use this one.. https://github.com/ArknightsAssets/ArknightsAssets

Also I wasn't sure if your question was about translating the actual text on the web page to chinese, there is some work needed to support that (using templates in html instead of raw string) but if you want you could send me a version of index.html translated to chinese.

**Comment by 30000lightyears** [comment]
maybe consider this: https://github.com/Kengxxiao/ArknightsGameData

**Comment by 30000lightyears** [comment]
i see now i can type chinese and guess, thanks!

**Comment by stripedypaper** [comment]
I already use ArknightsGameData for the skin data, but images are from elsewhere. I pushed a strings file which currently doesn't do anything but if you want to contribute translations for chinese you can submit a pull request for that file and I can hook up translations later.

https://github.com/stripedypaper/stripedypaper.github.io/blob/a284b99b85cbb6ad4fbe2e4921ef0cfd19623ccb/ak-guesser/strings.js
